# Generated by Django 4.1.3 on 2022-12-22 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/no-image.jpg', upload_to='posts', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
