# Generated by Django 4.1.3 on 2023-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('SEND', 'Send'), ('ACC', 'Accept'), ('CAN', 'Cancel')], max_length=6),
        ),
    ]
